CREATE PUBLIC SYNONYM ADMIN FOR EQDAW02.ADMINISTRADOR;
CREATE PUBLIC SYNONYM ASIS FOR EQDAW02.ASISTENTE;
CREATE PUBLIC SYNONYM CALEN FOR EQDAW02.CALENDARIO;
CREATE PUBLIC SYNONYM DUEN FOR EQDAW02.DUENO;
CREATE PUBLIC SYNONYM ENTR FOR EQDAW02.ENTRENADOR;
CREATE PUBLIC SYNONYM EQUI FOR EQDAW02.EQUIPO;
CREATE PUBLIC SYNONYM FICH FOR EQDAW02.FICHERO;
CREATE PUBLIC SYNONYM G_USER FOR EQDAW02.GRUPO_USUARIO;
CREATE PUBLIC SYNONYM JORN FOR EQDAW02.JORNADA;
CREATE PUBLIC SYNONYM JUGA FOR EQDAW02.JUGADOR;
CREATE PUBLIC SYNONYM PART FOR EQDAW02.PARTIDO;
CREATE PUBLIC SYNONYM RESUL FOR EQDAW02.RESULTADO;
CREATE PUBLIC SYNONYM POSICIONES FOR EQDAW02.ROL;

select *
from user_synonyms;